# Generated by Django 4.2.1 on 2023-05-06 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('dr_num', models.AutoField(help_text='System generated number uniquely identifying the driver', primary_key=True, serialize=False, verbose_name='Number')),
                ('dr_code', models.CharField(help_text='A number/code by which driver is identified by', max_length=100, verbose_name='Assigned Code')),
                ('dr_licence_no', models.CharField(help_text='Driver s licence number', max_length=100, verbose_name='Licence No')),
                ('dr_class', models.CharField(help_text='Class of vehicle driver licensed to drive', max_length=1, verbose_name='Class')),
                ('dr_licence_date', models.DateTimeField(help_text='Date drver obtained license', verbose_name='Licensed Date')),
                ('dr_fname', models.CharField(help_text='The driver s name', max_length=100, verbose_name='Vendor Name')),
                ('dr_sname', models.CharField(help_text='The driver s surname', max_length=100, verbose_name='Surname')),
                ('dr_gender', models.CharField(help_text='Gender of driver', max_length=1, verbose_name='Gender')),
                ('dr_dob', models.DateTimeField(help_text='Date of birth', verbose_name='Date Born')),
                ('dr_start_date', models.DateTimeField(help_text='Date joined', verbose_name='Start Date')),
                ('ad_user_c', models.CharField(blank=True, help_text='The user creating the record', max_length=30, null=True)),
                ('ad_user_a', models.CharField(blank=True, help_text='The last amending user', max_length=30, null=True)),
                ('ad_date_c', models.DateTimeField(auto_now_add=True, help_text='Date record was created')),
                ('ad_date_a', models.DateTimeField(auto_now=True, help_text='Date record was last amended')),
                ('ad_device_c', models.CharField(blank=True, help_text='The Device creating the record', max_length=100, null=True)),
                ('ad_device_a', models.CharField(blank=True, help_text='The Last amending device', max_length=100, null=True)),
                ('ad_ipadress_c', models.CharField(blank=True, help_text='The record creating ip address', max_length=50, null=True)),
                ('ad_ipadress_a', models.CharField(blank=True, help_text='The last amending ip address', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'ordering': ['dr_sname'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vn_nun', models.AutoField(help_text='System generated number uniquely identifying the vendor', primary_key=True, serialize=False, verbose_name='Number')),
                ('vn_code', models.CharField(help_text='A number/code by which vendor is identified by', max_length=100, verbose_name='Assigned Code')),
                ('vn_name', models.CharField(help_text='The vendor s name', max_length=200, verbose_name='Vendor Name')),
                ('vn_contact', models.CharField(help_text='Vendor contact person', max_length=100, verbose_name='Contact Person')),
                ('vn_phone_1', models.IntegerField(help_text='Contact person phone number', verbose_name='Phone')),
                ('vn_phone_2', models.IntegerField(help_text='Contact person phone number', verbose_name='Phone')),
                ('vn_email', models.EmailField(help_text='Email address', max_length=200, verbose_name='Email')),
                ('vn_address', models.CharField(help_text='The vendor s Physical Address line', max_length=200, verbose_name='Physical Address')),
                ('ad_user_c', models.CharField(blank=True, help_text='The user creating the record', max_length=30, null=True)),
                ('ad_user_a', models.CharField(blank=True, help_text='The last amending user', max_length=30, null=True)),
                ('ad_date_c', models.DateTimeField(auto_now_add=True, help_text='Date record was created')),
                ('ad_date_a', models.DateTimeField(auto_now=True, help_text='Date record was last amended')),
                ('ad_device_c', models.CharField(blank=True, help_text='The Device creating the record', max_length=100, null=True)),
                ('ad_device_a', models.CharField(blank=True, help_text='The Last amending device', max_length=100, null=True)),
                ('ad_ipadress_c', models.CharField(blank=True, help_text='The record creating ip address', max_length=50, null=True)),
                ('ad_ipadress_a', models.CharField(blank=True, help_text='The last amending ip address', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'ordering': ['vn_name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vh_num', models.AutoField(help_text='System generated number uniquely identifying the driver', primary_key=True, serialize=False, verbose_name='Number')),
                ('vh_code', models.CharField(help_text='A number/code by which veicle is identified by', max_length=100, verbose_name='Assigned Code')),
                ('vh_reg_num', models.CharField(help_text='Vehicle s registration number', max_length=100, verbose_name='Reg. No')),
                ('vh_model', models.CharField(help_text='Vehicle Model', max_length=100, verbose_name='Model')),
                ('vh_make', models.CharField(help_text='Make of vehicle', max_length=100, verbose_name='Make')),
                ('vh_type', models.CharField(help_text='Vehicle type', max_length=1, verbose_name='Type')),
                ('vh_reg_date', models.DateTimeField(help_text='Date registered', verbose_name='Reg. Date')),
                ('ad_user_c', models.CharField(blank=True, help_text='The user creating the record', max_length=30, null=True)),
                ('ad_user_a', models.CharField(blank=True, help_text='The last amending user', max_length=30, null=True)),
                ('ad_date_c', models.DateTimeField(auto_now_add=True, help_text='Date record was created')),
                ('ad_date_a', models.DateTimeField(auto_now=True, help_text='Date record was last amended')),
                ('ad_device_c', models.CharField(blank=True, help_text='The Device creating the record', max_length=100, null=True)),
                ('ad_device_a', models.CharField(blank=True, help_text='The Last amending device', max_length=100, null=True)),
                ('ad_ipadress_c', models.CharField(blank=True, help_text='The record creating ip address', max_length=50, null=True)),
                ('ad_ipadress_a', models.CharField(blank=True, help_text='The last amending ip address', max_length=50, null=True)),
                ('vh_vn_num', models.ForeignKey(help_text='Vendor', on_delete=django.db.models.deletion.CASCADE, to='star_track.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'ordering': ['vh_code'],
            },
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('cn_num', models.AutoField(help_text='System generated number uniquely identifying the consignment', primary_key=True, serialize=False, verbose_name='Number')),
                ('cn_code', models.CharField(help_text='A number/code by which consignment is identified by', max_length=100, verbose_name='Assigned Code')),
                ('cn_ref', models.CharField(help_text='Consignment s reference number', max_length=100, verbose_name='Reference')),
                ('cn_from', models.CharField(help_text='Consignment s origin', max_length=100, verbose_name='Origin')),
                ('cn_booked_date', models.DateTimeField(help_text='Date truck is booked', verbose_name='Booked Date')),
                ('cn_in_date', models.DateTimeField(help_text='Entry date of truck entry', verbose_name='Entry Date')),
                ('cn_in_weight', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='In weight', max_digits=15, null=True, verbose_name='In Weight')),
                ('cn_in_units', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='In Units', max_digits=15, null=True, verbose_name='In Units')),
                ('cn_out_date', models.DateTimeField(help_text='Date and time of truck exit', verbose_name='Exit Date')),
                ('cn_out_wght', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Out Weight', max_digits=15, null=True, verbose_name='Out Weight')),
                ('cn_out_units', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Out Units', max_digits=15, null=True, verbose_name='Out Units')),
                ('cn_remarks', models.CharField(help_text='Remarks on consignment', max_length=200, verbose_name='Remarks')),
                ('cn_comment', models.CharField(help_text='Comment on consignment', max_length=200, verbose_name='Comment')),
                ('cn_status', models.CharField(help_text='Consignment s status', max_length=1, verbose_name='Status')),
                ('ad_user_c', models.CharField(blank=True, help_text='The user creating the record', max_length=30, null=True)),
                ('ad_user_a', models.CharField(blank=True, help_text='The last amending user', max_length=30, null=True)),
                ('ad_date_c', models.DateTimeField(auto_now_add=True, help_text='Date record was created')),
                ('ad_date_a', models.DateTimeField(auto_now=True, help_text='Date record was last amended')),
                ('ad_device_c', models.CharField(blank=True, help_text='The Device creating the record', max_length=100, null=True)),
                ('ad_device_a', models.CharField(blank=True, help_text='The Last amending device', max_length=100, null=True)),
                ('ad_ipadress_c', models.CharField(blank=True, help_text='The record creating ip address', max_length=50, null=True)),
                ('ad_ipadress_a', models.CharField(blank=True, help_text='The last amending ip address', max_length=50, null=True)),
                ('cn_dr_num', models.ForeignKey(help_text='Driver', on_delete=django.db.models.deletion.CASCADE, to='star_track.driver', verbose_name='Driver')),
                ('cn_vh_num', models.ForeignKey(help_text='Vehicle', on_delete=django.db.models.deletion.CASCADE, to='star_track.vehicle', verbose_name='Vehicle')),
                ('cn_vn_num', models.ForeignKey(help_text='Vendor', on_delete=django.db.models.deletion.CASCADE, to='star_track.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Consignment',
                'ordering': ['cn_code'],
            },
        ),
    ]
