# Generated by Django 4.2.1 on 2023-05-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='cn_comment',
            field=models.CharField(blank=True, help_text='Comment on consignment', max_length=200, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='cn_in_date',
            field=models.DateTimeField(blank=True, help_text='Entry date of truck entry', null=True, verbose_name='Entry Date'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='cn_remarks',
            field=models.CharField(blank=True, help_text='Remarks on consignment', max_length=200, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='cn_status',
            field=models.CharField(blank=True, help_text='Consignment s status', max_length=1, null=True, verbose_name='Status'),
        ),
    ]
