# Generated by Django 4.2.1 on 2023-05-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_track', '0004_alter_driver_dr_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='cn_out_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of truck exit', null=True, verbose_name='Exit Date'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='cn_status',
            field=models.CharField(blank=True, choices=[('1', 'Planned'), ('2', 'Loaded'), ('3', 'In Transit'), ('4', 'Landed')], help_text='Consignment s status', max_length=1, null=True, verbose_name='Status'),
        ),
    ]
