# Generated by Django 4.2.1 on 2023-05-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_track', '0005_alter_consignment_cn_out_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['vh_reg_num'], 'verbose_name': 'Vehicle'},
        ),
        migrations.AddField(
            model_name='consignment',
            name='cn_confirmed',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No')], default='N', help_text='Consignment s confirmation status', max_length=1, null=True, verbose_name='Confirmed'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='cn_pl_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Planned weight', max_digits=15, null=True, verbose_name='Planned Weight'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='cn_status',
            field=models.CharField(blank=True, choices=[('1', 'Planned'), ('2', 'Loaded'), ('3', 'In Transit'), ('4', 'Landed')], default='1', help_text='Consignment s status', max_length=1, null=True, verbose_name='Status'),
        ),
    ]
