# Generated by Django 4.2.1 on 2023-05-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_track', '0006_alter_vehicle_options_consignment_cn_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='cn_type',
            field=models.CharField(blank=True, choices=[('1', 'Inbound'), ('2', 'Off-Take')], default='1', help_text='Consignment type', max_length=1, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='cn_booked_date',
            field=models.DateTimeField(help_text='Date consignment is booked', verbose_name='Booked Date'),
        ),
    ]
